/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import static com.sun.deploy.uitoolkit.impl.fx.ui.MixedCodeInSwing.show;

/**
 *
 * @author Juan Carranza
 */
public class NewJFrame extends javax.swing.JFrame {

    int int_vida = 1000;
    int int_vida2 = 2000;
    int int_vida3 = 3000;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ataque = new javax.swing.JButton();
        Vida = new javax.swing.JProgressBar();
        Vida2 = new javax.swing.JProgressBar();
        Ataque2 = new javax.swing.JButton();
        Curar = new javax.swing.JButton();
        Vida3 = new javax.swing.JProgressBar();
        Ataque3 = new javax.swing.JButton();
        Resultado = new javax.swing.JLabel();
        Heroes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ataque.setText("Ataque");
        Ataque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtaqueMousePressed(evt);
            }
        });
        Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueActionPerformed(evt);
            }
        });

        Vida.setMaximum(1000);

        Vida2.setMaximum(2000);

        Ataque2.setText("Ataque");
        Ataque2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ataque2MousePressed(evt);
            }
        });

        Curar.setText("Curar");
        Curar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CurarMousePressed(evt);
            }
        });

        Vida3.setMaximum(3000);

        Ataque3.setText("Ataque");
        Ataque3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Ataque3MousePressed(evt);
            }
        });
        Ataque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ataque3ActionPerformed(evt);
            }
        });

        Resultado.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                ResultadoComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ResultadoComponentShown(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PieceDragon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g10079.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descarga (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(Vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Ataque))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Ataque2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(585, 585, 585)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Vida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ataque3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Curar)))
                                .addContainerGap(122, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Heroes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ataque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ataque2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Vida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Ataque3)
                                    .addComponent(Curar))
                                .addGap(57, 57, 57)
                                .addComponent(Heroes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtaqueActionPerformed

    private void AtaqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtaqueMousePressed
        // TODO add your handling code here:
        Vida3.setValue(int_vida3);
        int_vida3 -= 50;
          if(int_vida < 0 && int_vida2 < 0){
         Resultado.setText("Evil Wins");
         System.out.print(Resultado);
      }
        else{
          Resultado.setText("Heroes Wins");
          System.out.print(Resultado);
      }
    }//GEN-LAST:event_AtaqueMousePressed

    private void Ataque2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ataque2MousePressed
        // TODO add your handling code here:
        Vida3.setValue(int_vida3);
        int_vida3 -= 40;
           if(int_vida < 0 && int_vida2 < 0){
         Resultado.setText("Evil Wins");
         System.out.print(Resultado);
      } 
        else{
          Resultado.setText("Heroes Wins");
          System.out.print(Resultado);
      }
        
    }//GEN-LAST:event_Ataque2MousePressed

    private void CurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurarMousePressed
        // TODO add your handling code here:
        Vida3.setValue(int_vida3);
        int_vida3 += 25;
        
        
    }//GEN-LAST:event_CurarMousePressed

    private void Ataque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ataque3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ataque3ActionPerformed

    private void Ataque3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ataque3MousePressed
        // TODO add your handling code here:
        Vida.setValue(int_vida);
        int_vida -= 30;
        
        Vida2.setValue(int_vida2);
        int_vida2 -= 30;
           if(int_vida < 0 && int_vida2 < 0){
         Resultado.setText("Evil Wins");
         System.out.print(Resultado);
      }
      else{
          Resultado.setText("Heroes Wins");
          System.out.print(Resultado);
      }
        
        
    }//GEN-LAST:event_Ataque3MousePressed

    private void ResultadoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ResultadoComponentHidden
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoComponentHidden

    private void ResultadoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ResultadoComponentShown
        // TODO add your handling code here:
      
      if(int_vida < 0 && int_vida2 < 0){
         Resultado.setText("Evil Wins");
         System.out.print(Resultado);
      }
      else{
          Resultado.setText("Heroes Wins");
          System.out.print(Resultado);
      }
       
    }//GEN-LAST:event_ResultadoComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ataque;
    private javax.swing.JButton Ataque2;
    private javax.swing.JButton Ataque3;
    private javax.swing.JButton Curar;
    private javax.swing.JLabel Heroes;
    private javax.swing.JLabel Resultado;
    private javax.swing.JProgressBar Vida;
    private javax.swing.JProgressBar Vida2;
    private javax.swing.JProgressBar Vida3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
